apiVersion: v2
name: fraud-detection
description: Helm chart for the Fraud Detection Platform
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: redis
    version: "18.6.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: kafka
    version: "26.8.0"
    repository: "https://charts.bitnami.com/bitnami"
    condition: kafka.enabled

maintainers:
  - name: Fraud Detection Team
    email: fraud-team@bank.com
