// Code generated by protoc-gen-go. DO NOT EDIT.
// In production, run: protoc --go_out=. --go-grpc_out=. fraud.proto
// This is a hand-written stub for local development.

package proto

import (
	"context"
)

// ─── Enums ───────────────────────────────────────────────────────────────────

type Decision int32

const (
	Decision_APPROVE Decision = 0
	Decision_REVIEW  Decision = 1
	Decision_DECLINE Decision = 2
)

// ─── Messages ────────────────────────────────────────────────────────────────

type ScoreRequest struct {
	TransactionId string            `json:"transaction_id"`
	Features      map[string]string `json:"features"`
	ModelVersion  string            `json:"model_version"`
	TimestampMs   int64             `json:"timestamp_ms"`
}

type ScoreResponse struct {
	TransactionId    string             `json:"transaction_id"`
	Decision         Decision           `json:"decision"`
	FraudProbability float64            `json:"fraud_probability"`
	ModelVersion     string             `json:"model_version"`
	LatencyMs        int64              `json:"latency_ms"`
	TopFeatures      map[string]float64 `json:"top_features"`
	ReasonCode       string             `json:"reason_code"`
}

type DecisionResponse struct {
	TransactionId string   `json:"transaction_id"`
	Decision      Decision `json:"decision"`
	TimestampMs   int64    `json:"timestamp_ms"`
}

type StringRequest struct {
	Value string `json:"value"`
}

type Empty struct{}

type HealthResponse struct {
	Healthy         bool   `json:"healthy"`
	ModelVersion    string `json:"model_version"`
	ModelLoadedAtMs int64  `json:"model_loaded_at_ms"`
	UptimeSeconds   int64  `json:"uptime_seconds"`
}

// ─── Service Interface ───────────────────────────────────────────────────────

type FraudScoringServiceServer interface {
	ScoreTransaction(ctx context.Context, req *ScoreRequest) (*ScoreResponse, error)
	GetDecision(ctx context.Context, req *StringRequest) (*DecisionResponse, error)
	HealthCheck(ctx context.Context, req *Empty) (*HealthResponse, error)
	ScoreBatch(stream FraudScoringService_ScoreBatchServer) error
}

type FraudScoringService_ScoreBatchServer interface {
	Recv() (*ScoreRequest, error)
	Send(*ScoreResponse) error
	Context() context.Context
}

type UnimplementedFraudScoringServiceServer struct{}

func (UnimplementedFraudScoringServiceServer) ScoreTransaction(context.Context, *ScoreRequest) (*ScoreResponse, error) {
	return nil, nil
}
func (UnimplementedFraudScoringServiceServer) GetDecision(context.Context, *StringRequest) (*DecisionResponse, error) {
	return nil, nil
}
func (UnimplementedFraudScoringServiceServer) HealthCheck(context.Context, *Empty) (*HealthResponse, error) {
	return nil, nil
}
func (UnimplementedFraudScoringServiceServer) ScoreBatch(FraudScoringService_ScoreBatchServer) error {
	return nil
}

// ─── Registration (no-op stub) ──────────────────────────────────────────────

func RegisterFraudScoringServiceServer(srv interface{}, svc FraudScoringServiceServer) {
	// In production, this registers with a real gRPC server.
	// Stub for compilation.
}
